### ISSUE TITLE
Hackintosh-OpenCore-HP-9470m-1366x768  bigsur

### ISSUE THREAD

**Issue by michelafshin** [hackintosh107/Hackintosh-OpenCore-HP-9470m-1366x768#1]
hello sir thank you for your great work. i just can not make trackpad work i wonder why, i hope you can help thanks

**Comment by cricri207** [comment]
Hi Michel,

I also used the files to install Catalina and had also no trackpad.
I could find a workaround in adding 2 kext at boot : VoodooI2CHID.kext and VoodooI2Synaptics.kext.

You will need to update your config.plist but after trackpad runs.

But I am still stucked with no gestures, so I continue to found how to solve that point.

Chris

**Comment by cricri207** [comment]
> hello sir thank you for your great work. i just can not make trackpad work i wonder why, i hope you can help thanks

Hi Michel,

I also used the files to install Catalina and had also no trackpad.
I could find a workaround in adding 2 kext at boot : VoodooI2CHID.kext and VoodooI2Synaptics.kext.

You will need to update your config.plist but after trackpad runs.

But I am still stucked with no gestures, so I continue to found how to solve that point.

Chris

**Comment by michelafshin** [comment]
THANKS FOR YOUR RESPOND 👍

Den fre. 15. jan. 2021 kl. 14.10 skrev cricri207 <notifications@github.com>:

**Comment by michelafshin** [comment]
Try This EFI for Catalina 10.15.7 HP-9470m-1366x768 works 100%

**Comment by cricri207** [comment]
Hi Michel,

I finaly succeded in having gestures with help of this forum (https://hackintosher.com/forums/thread/touchpad-scrolling-not-working.10442/).

I understood that when there is no trackpad recognized in parameters and trackpad is working with no gesture means that trackpad is acting as a mouse.

I just disable 2 kexts : VoodooPS2Mouse and VoodooPS2Touchpad in config.plist (no need to remove the kexts from EFI) and gestures will run. Removing only VoodooPS2Mouse or only VoodooPS2Touchpad is not enough.

Of course, the 2 previous kext that were mentionned have to be installed (VoodooI2CHID and VoodooI2CSynaptics).

Cheers

**Comment by michelafshin** [comment]
very nice thanks

Den lør. 16. jan. 2021 kl. 17.43 skrev cricri207 <notifications@github.com>:
